### PR TITLE
add: Import of Related / Cross-Sell / UP-Sell for products

### PR DESCRIPTION
**Pull request by spipu**

### CODE REVIEW

**Comment by spipu** [comment]
hi, is there a pb on this pull request ?

**Comment by julienanquetil** [comment]
Bump this one cause it's look very promissing 👍

**Comment by magentix** [comment]
Hi,

Sorry for the delay, this is now merged :)

Thanks a lot @spipu !

**Comment by spipu** [comment]
no pb, thks to you for this module :)

**Pull request merged**
